language: ruby
rvm:
  - ruby 2.0.0-p247
env:
  - DB=postgresql
before_script:
  - psql -c 'create database agile2go_test' -U postgres
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - bundle exec puma faye/config.ru 9292
  - sleep 3
script:
  - bundle exec rake db:drop
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - bundle exec rake
  - bundle exec rake jasmine:ci
