development:
  adapter: postgresql
  database: agile2go
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: agile2go_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: agile2go
  pool: 5
  timeout: 5000
