defaults: &defaults
  host: 127.0.0.1
  port: 27017
  options:
    w: 1
    pool_size: 1
    slave_ok: false

development:
  <<: *defaults
  database: agile2go_development

test:
  <<: *defaults
  database: agile2go_test
  w: 0

production:
  uri: <%= ENV['MONGODB_URL'] %>
